package main

/*
Apache License 2.0

Copyright 2026 Shane

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import (
	"bytes"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"

	cryptosv1 "github.com/CryptOS-PKI/api/go/cryptos/v1"
)

// runCmd executes the root command with args against no server; it is used
// to exercise the pre-dial argument validation.
func runCmd(t *testing.T, args ...string) (string, error) {
	t.Helper()
	root := newRootCmd()
	var buf bytes.Buffer
	root.SetOut(&buf)
	root.SetErr(&buf)
	root.SetArgs(args)
	err := root.Execute()
	return buf.String(), err
}

func TestSignSubordinateRequiresFlags(t *testing.T) {
	if _, err := runCmd(t, "ca", "sign-subordinate", "--profile", "issuing"); err == nil {
		t.Error("sign-subordinate without --csr = nil, want error")
	}
	if _, err := runCmd(t, "ca", "sign-subordinate", "--csr", "x.csr"); err == nil {
		t.Error("sign-subordinate without --profile = nil, want error")
	}
}

func TestIssueLeafRegistered(t *testing.T) {
	ca := newCACmd(&globalOpts{})
	var found *cobra.Command
	for _, sub := range ca.Commands() {
		if sub.Name() == "issue-leaf" {
			found = sub
			break
		}
	}
	if found == nil {
		t.Fatal("issue-leaf not registered under ca")
	}
	if found.Flags().Lookup("csr") == nil {
		t.Error("issue-leaf missing --csr flag")
	}
	if found.Flags().Lookup("profile") == nil {
		t.Error("issue-leaf missing --profile flag")
	}
}

func TestIssueLeafRequiresFlags(t *testing.T) {
	if _, err := runCmd(t, "ca", "issue-leaf", "--profile", "server"); err == nil {
		t.Error("issue-leaf without --csr = nil, want error")
	}
	if _, err := runCmd(t, "ca", "issue-leaf", "--csr", "x.csr"); err == nil {
		t.Error("issue-leaf without --profile = nil, want error")
	}
}

func TestSubmitSubordinateCertRequiresChain(t *testing.T) {
	if _, err := runCmd(t, "ca", "submit-subordinate-cert"); err == nil {
		t.Error("submit-subordinate-cert without --chain = nil, want error")
	}
}

func TestRotateKeyRegistered(t *testing.T) {
	ca := newCACmd(&globalOpts{})
	names := map[string]bool{}
	for _, sub := range ca.Commands() {
		names[sub.Name()] = true
	}
	if !names["rotate-key"] {
		t.Error("rotate-key not registered under ca")
	}
	if !names["submit-rotation"] {
		t.Error("submit-rotation not registered under ca")
	}
}

func TestSubmitRotationRequiresChain(t *testing.T) {
	if _, err := runCmd(t, "ca", "submit-rotation"); err == nil {
		t.Error("submit-rotation without --chain = nil, want error")
	}
}

func TestDecodeCSR(t *testing.T) {
	der := testCSR(t)
	pemOf := func(blockType string) string {
		return string(pem.EncodeToMemory(&pem.Block{Type: blockType, Bytes: der}))
	}
	crlf := func(s string) string { return strings.ReplaceAll(s, "\n", "\r\n") }

	tests := []struct {
		name    string
		in      []byte
		wantErr string
	}{
		{name: "standard PEM", in: []byte(pemOf("CERTIFICATE REQUEST"))},
		{name: "NEW CERTIFICATE REQUEST PEM", in: []byte(pemOf("NEW CERTIFICATE REQUEST"))},
		{name: "CRLF line endings", in: []byte(crlf(pemOf("NEW CERTIFICATE REQUEST")))},
		{
			name: "surrounding text",
			in:   []byte(crlf("Request generated by certreq\n\n" + pemOf("NEW CERTIFICATE REQUEST") + "\ntrailing notes\n")),
		},
		{
			name: "request after another block",
			in:   []byte(pemOf("CERTIFICATE") + pemOf("CERTIFICATE REQUEST")),
		},
		{name: "raw DER", in: der},
		{name: "wrong block type", in: []byte(pemOf("CERTIFICATE")), wantErr: `found "CERTIFICATE"`},
		{name: "empty file", in: nil, wantErr: "empty"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := decodeCSR(tt.in)
			if tt.wantErr != "" {
				if err == nil || !strings.Contains(err.Error(), tt.wantErr) {
					t.Fatalf("decodeCSR() err = %v, want containing %q", err, tt.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("decodeCSR(): %v", err)
			}
			if !bytes.Equal(got, der) {
				t.Error("decodeCSR() did not return the CSR DER")
			}
		})
	}
}

func TestReadCSRDER(t *testing.T) {
	der := testCSR(t)
	path := filepath.Join(t.TempDir(), "req.txt")
	writeFile(t, path, pem.EncodeToMemory(&pem.Block{Type: "NEW CERTIFICATE REQUEST", Bytes: der}))
	got, err := readCSRDER(path)
	if err != nil {
		t.Fatalf("readCSRDER: %v", err)
	}
	if !bytes.Equal(got, der) {
		t.Error("readCSRDER did not return the CSR DER")
	}
	if _, err := readCSRDER(filepath.Join(t.TempDir(), "missing")); err == nil {
		t.Error("readCSRDER(missing) = nil, want error")
	}
}

// testCSR returns a freshly generated PKCS#10 request in DER form.
func testCSR(t *testing.T) []byte {
	t.Helper()
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("GenerateKey: %v", err)
	}
	der, err := x509.CreateCertificateRequest(rand.Reader, &x509.CertificateRequest{
		Subject: pkix.Name{CommonName: "dc02.ad.example.org"},
	}, key)
	if err != nil {
		t.Fatalf("CreateCertificateRequest: %v", err)
	}
	return der
}

func TestChainToDER(t *testing.T) {
	leaf := selfSignedCA(t)
	root := selfSignedCA(t)
	var buf bytes.Buffer
	_ = pem.Encode(&buf, &pem.Block{Type: "CERTIFICATE", Bytes: leaf})
	_ = pem.Encode(&buf, &pem.Block{Type: "CERTIFICATE", Bytes: root})

	chain, err := chainToDER(buf.Bytes())
	if err != nil {
		t.Fatalf("chainToDER: %v", err)
	}
	if len(chain) != 2 || !bytes.Equal(chain[0], leaf) || !bytes.Equal(chain[1], root) {
		t.Errorf("chainToDER returned %d certs, want leaf-first 2", len(chain))
	}

	if _, err := chainToDER(nil); err == nil {
		t.Error("chainToDER(nil) = nil, want error")
	}
}

func TestWriteChainPEM(t *testing.T) {
	// Prefers server PEM when present.
	var buf bytes.Buffer
	if err := writeChainPEM(&buf, "PEM-STRING", [][]byte{[]byte("ignored")}); err != nil {
		t.Fatalf("writeChainPEM(pem): %v", err)
	}
	if buf.String() != "PEM-STRING" {
		t.Errorf("writeChainPEM prefers PEM, got %q", buf.String())
	}

	// Encodes DER when no PEM.
	der := selfSignedCA(t)
	buf.Reset()
	if err := writeChainPEM(&buf, "", [][]byte{der}); err != nil {
		t.Fatalf("writeChainPEM(der): %v", err)
	}
	if !strings.Contains(buf.String(), "BEGIN CERTIFICATE") {
		t.Errorf("writeChainPEM(der) produced no PEM: %q", buf.String())
	}

	if err := writeChainPEM(&buf, "", nil); err == nil {
		t.Error("writeChainPEM(empty) = nil, want error")
	}
}

func TestWritePEMBlock(t *testing.T) {
	der := selfSignedCA(t)
	var buf bytes.Buffer
	if err := writePEMBlock(&buf, "CERTIFICATE REQUEST", der); err != nil {
		t.Fatalf("writePEMBlock: %v", err)
	}
	if !strings.Contains(buf.String(), "BEGIN CERTIFICATE REQUEST") {
		t.Errorf("writePEMBlock produced wrong block: %q", buf.String())
	}
	if err := writePEMBlock(&buf, "CERTIFICATE REQUEST", nil); err == nil {
		t.Error("writePEMBlock(empty) = nil, want error")
	}
}

func TestWriteIdentity(t *testing.T) {
	der := selfSignedCA(t)
	id := &cryptosv1.Identity{
		ChainDer: [][]byte{der},
		ChainPem: string(pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})),
	}
	var buf bytes.Buffer
	if err := writeIdentity(&buf, id, formatPEM); err != nil {
		t.Fatalf("writeIdentity(pem): %v", err)
	}
	if !strings.Contains(buf.String(), "BEGIN CERTIFICATE") {
		t.Errorf("writeIdentity(pem) missing cert: %q", buf.String())
	}

	buf.Reset()
	if err := writeIdentity(&buf, id, formatHuman); err != nil {
		t.Fatalf("writeIdentity(human): %v", err)
	}
	if !strings.Contains(buf.String(), "Subject:") {
		t.Errorf("writeIdentity(human) missing summary: %q", buf.String())
	}
}
